[tool.codespell]
ignore-words-list = "nd"

[tool.mdformat]
number = true

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
profile = "black"

# https://github.com/PyCQA/pydocstyle/issues/418
[tool.pydocstyle]
add_ignore = "D205, D400, D101, D102, D103, D105, D107"

[tool.bandit]
skips = ["B101"]

[tool.bandit.assert_used]
skips = ["*_test.py", "test_*.py"]
number = true
