---
"on":
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  python-version: 3.x
  cache: pip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{env.python-version}}
          cache: ${{env.cache}}
          cache-dependency-path: |-
            requirements.txt
      - name: Install dependencies
        run: |
          pip install -rrequirements.txt
      - name: Build
        run: |
          meson setup build project-spec/meta-user/recipes-apps/autostart
          meson compile -Cbuild
          # meson test -Cbuild
          meson dist -Cbuild
      # - uses: codecov/codecov-action@v3
      #   with:
      #     gcov: true
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          path: |
            build/meson-dist/*.tar.xz
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # body_path: build/CHANGELOG.md
          files: |
            build/meson-dist/*.tar.xz
